global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Temporarily disable alert rules until metrics are available
# rule_files:
#   - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # AgentHub Broker - Only service we want to monitor
  - job_name: 'agenthub-broker'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s