// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/a2a_core.proto

package a2a

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A2A Role enum following the specification
type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_ROLE_USER        Role = 1
	Role_ROLE_AGENT       Role = 2
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_USER",
		2: "ROLE_AGENT",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_USER":        1,
		"ROLE_AGENT":       2,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_a2a_core_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_proto_a2a_core_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_proto_a2a_core_proto_rawDescGZIP(), []int{0}
}

// A2A Task State following the specification exactly
type TaskState int32

const (
	TaskState_TASK_STATE_UNSPECIFIED    TaskState = 0
	TaskState_TASK_STATE_SUBMITTED      TaskState = 1 // Acknowledged but not started
	TaskState_TASK_STATE_WORKING        TaskState = 2 // Actively being processed
	TaskState_TASK_STATE_COMPLETED      TaskState = 3 // Successfully finished
	TaskState_TASK_STATE_FAILED         TaskState = 4 // Failed with error
	TaskState_TASK_STATE_CANCELLED      TaskState = 5 // Cancelled before completion
	TaskState_TASK_STATE_INPUT_REQUIRED TaskState = 6 // Waiting for more input
	TaskState_TASK_STATE_REJECTED       TaskState = 7 // Agent declined to do task
	TaskState_TASK_STATE_AUTH_REQUIRED  TaskState = 8 // Needs authentication
)

// Enum value maps for TaskState.
var (
	TaskState_name = map[int32]string{
		0: "TASK_STATE_UNSPECIFIED",
		1: "TASK_STATE_SUBMITTED",
		2: "TASK_STATE_WORKING",
		3: "TASK_STATE_COMPLETED",
		4: "TASK_STATE_FAILED",
		5: "TASK_STATE_CANCELLED",
		6: "TASK_STATE_INPUT_REQUIRED",
		7: "TASK_STATE_REJECTED",
		8: "TASK_STATE_AUTH_REQUIRED",
	}
	TaskState_value = map[string]int32{
		"TASK_STATE_UNSPECIFIED":    0,
		"TASK_STATE_SUBMITTED":      1,
		"TASK_STATE_WORKING":        2,
		"TASK_STATE_COMPLETED":      3,
		"TASK_STATE_FAILED":         4,
		"TASK_STATE_CANCELLED":      5,
		"TASK_STATE_INPUT_REQUIRED": 6,
		"TASK_STATE_REJECTED":       7,
		"TASK_STATE_AUTH_REQUIRED":  8,
	}
)

func (x TaskState) Enum() *TaskState {
	p := new(TaskState)
	*p = x
	return p
}

func (x TaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_a2a_core_proto_enumTypes[1].Descriptor()
}

func (TaskState) Type() protoreflect.EnumType {
	return &file_proto_a2a_core_proto_enumTypes[1]
}

func (x TaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskState.Descriptor instead.
func (TaskState) EnumDescriptor() ([]byte, []int) {
	return file_proto_a2a_core_proto_rawDescGZIP(), []int{1}
}

// A2A Part (content union type)
type Part struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Part:
	//
	//	*Part_Text
	//	*Part_File
	//	*Part_Data
	Part          isPart_Part      `protobuf_oneof:"part"`
	Metadata      *structpb.Struct `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"` // Optional part-specific metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Part) Reset() {
	*x = Part{}
	mi := &file_proto_a2a_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Part) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Part) ProtoMessage() {}

func (x *Part) ProtoReflect() protoreflect.Message {
	mi := &file_proto_a2a_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Part.ProtoReflect.Descriptor instead.
func (*Part) Descriptor() ([]byte, []int) {
	return file_proto_a2a_core_proto_rawDescGZIP(), []int{0}
}

func (x *Part) GetPart() isPart_Part {
	if x != nil {
		return x.Part
	}
	return nil
}

func (x *Part) GetText() string {
	if x != nil {
		if x, ok := x.Part.(*Part_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *Part) GetFile() *FilePart {
	if x != nil {
		if x, ok := x.Part.(*Part_File); ok {
			return x.File
		}
	}
	return nil
}

func (x *Part) GetData() *DataPart {
	if x != nil {
		if x, ok := x.Part.(*Part_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *Part) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type isPart_Part interface {
	isPart_Part()
}

type Part_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"` // TextPart - plain text content
}

type Part_File struct {
	File *FilePart `protobuf:"bytes,2,opt,name=file,proto3,oneof"` // FilePart - file-based content
}

type Part_Data struct {
	Data *DataPart `protobuf:"bytes,3,opt,name=data,proto3,oneof"` // DataPart - structured JSON data
}

func (*Part_Text) isPart_Part() {}

func (*Part_File) isPart_Part() {}

func (*Part_Data) isPart_Part() {}

// A2A FilePart for file-based content
type FilePart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to File:
	//
	//	*FilePart_FileWithUri
	//	*FilePart_FileWithBytes
	File          isFilePart_File `protobuf_oneof:"file"`
	MimeType      string          `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"` // MIME type (e.g., "image/png")
	Name          string          `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                         // Optional filename
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilePart) Reset() {
	*x = FilePart{}
	mi := &file_proto_a2a_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilePart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePart) ProtoMessage() {}

func (x *FilePart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_a2a_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePart.ProtoReflect.Descriptor instead.
func (*FilePart) Descriptor() ([]byte, []int) {
	return file_proto_a2a_core_proto_rawDescGZIP(), []int{1}
}

func (x *FilePart) GetFile() isFilePart_File {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *FilePart) GetFileWithUri() string {
	if x != nil {
		if x, ok := x.File.(*FilePart_FileWithUri); ok {
			return x.FileWithUri
		}
	}
	return ""
}

func (x *FilePart) GetFileWithBytes() []byte {
	if x != nil {
		if x, ok := x.File.(*FilePart_FileWithBytes); ok {
			return x.FileWithBytes
		}
	}
	return nil
}

func (x *FilePart) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FilePart) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type isFilePart_File interface {
	isFilePart_File()
}

type FilePart_FileWithUri struct {
	FileWithUri string `protobuf:"bytes,1,opt,name=file_with_uri,json=fileWithUri,proto3,oneof"` // URI pointing to file content
}

type FilePart_FileWithBytes struct {
	FileWithBytes []byte `protobuf:"bytes,2,opt,name=file_with_bytes,json=fileWithBytes,proto3,oneof"` // Direct file content as bytes
}

func (*FilePart_FileWithUri) isFilePart_File() {}

func (*FilePart_FileWithBytes) isFilePart_File() {}

// A2A DataPart for structured data
type DataPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *structpb.Struct       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // JSON-like structured data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPart) Reset() {
	*x = DataPart{}
	mi := &file_proto_a2a_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPart) ProtoMessage() {}

func (x *DataPart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_a2a_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPart.ProtoReflect.Descriptor instead.
func (*DataPart) Descriptor() ([]byte, []int) {
	return file_proto_a2a_core_proto_rawDescGZIP(), []int{2}
}

func (x *DataPart) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

// A2A Message (core communication unit)
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // Required unique message ID
	ContextId     string                 `protobuf:"bytes,2,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"` // Groups related interactions
	TaskId        string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`          // Optional task association
	Role          Role                   `protobuf:"varint,4,opt,name=role,proto3,enum=a2a.Role" json:"role,omitempty"`             // "user" or "agent"
	Content       []*Part                `protobuf:"bytes,5,rep,name=content,proto3" json:"content,omitempty"`                      // The actual message content
	Metadata      *structpb.Struct       `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`                    // Optional message metadata
	Extensions    []string               `protobuf:"bytes,7,rep,name=extensions,proto3" json:"extensions,omitempty"`                // Extension URIs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_a2a_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_a2a_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_a2a_core_proto_rawDescGZIP(), []int{3}
}

func (x *Message) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Message) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *Message) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Message) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *Message) GetContent() []*Part {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Message) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Message) GetExtensions() []string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

// A2A TaskStatus
type TaskStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         TaskState              `protobuf:"varint,1,opt,name=state,proto3,enum=a2a.TaskState" json:"state,omitempty"` // Current task state
	Update        *Message               `protobuf:"bytes,2,opt,name=update,proto3" json:"update,omitempty"`                   // Status message from agent
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`             // When this status was recorded
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatus) Reset() {
	*x = TaskStatus{}
	mi := &file_proto_a2a_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatus) ProtoMessage() {}

func (x *TaskStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_a2a_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatus.ProtoReflect.Descriptor instead.
func (*TaskStatus) Descriptor() ([]byte, []int) {
	return file_proto_a2a_core_proto_rawDescGZIP(), []int{4}
}

func (x *TaskStatus) GetState() TaskState {
	if x != nil {
		return x.State
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

func (x *TaskStatus) GetUpdate() *Message {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *TaskStatus) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// A2A Task (stateful work unit)
type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                // Unique task identifier
	ContextId     string                 `protobuf:"bytes,2,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"` // Context grouping identifier
	Status        *TaskStatus            `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                        // Current task status
	Artifacts     []*Artifact            `protobuf:"bytes,4,rep,name=artifacts,proto3" json:"artifacts,omitempty"`                  // Output artifacts from task
	History       []*Message             `protobuf:"bytes,5,rep,name=history,proto3" json:"history,omitempty"`                      // Complete interaction history
	Metadata      *structpb.Struct       `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`                    // Custom task metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_a2a_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_a2a_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_a2a_core_proto_rawDescGZIP(), []int{5}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *Task) GetStatus() *TaskStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Task) GetArtifacts() []*Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *Task) GetHistory() []*Message {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *Task) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// A2A Artifact (task outputs)
type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"` // Unique ID within task
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                               // Human readable name
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                 // Optional description
	Parts         []*Part                `protobuf:"bytes,5,rep,name=parts,proto3" json:"parts,omitempty"`                             // Artifact content
	Metadata      *structpb.Struct       `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`                       // Optional artifact metadata
	Extensions    []string               `protobuf:"bytes,7,rep,name=extensions,proto3" json:"extensions,omitempty"`                   // Extension URIs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_proto_a2a_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_proto_a2a_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_proto_a2a_core_proto_rawDescGZIP(), []int{6}
}

func (x *Artifact) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *Artifact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Artifact) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Artifact) GetParts() []*Part {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *Artifact) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Artifact) GetExtensions() []string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

// Agent Card for agent discovery and capabilities
type AgentCard struct {
	state                             protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion                   string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`                                                             // A2A protocol version supported
	Name                              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                                                          // Human readable agent name
	Description                       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                                                                                            // Agent description
	Url                               string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`                                                                                                            // Primary service endpoint
	PreferredTransport                string                 `protobuf:"bytes,5,opt,name=preferred_transport,json=preferredTransport,proto3" json:"preferred_transport,omitempty"`                                                    // Preferred transport protocol
	AdditionalInterfaces              []*AgentInterface      `protobuf:"bytes,6,rep,name=additional_interfaces,json=additionalInterfaces,proto3" json:"additional_interfaces,omitempty"`                                              // Additional transport options
	Provider                          *AgentProvider         `protobuf:"bytes,7,opt,name=provider,proto3" json:"provider,omitempty"`                                                                                                  // Provider information
	Version                           string                 `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`                                                                                                    // Agent version
	DocumentationUrl                  string                 `protobuf:"bytes,9,opt,name=documentation_url,json=documentationUrl,proto3" json:"documentation_url,omitempty"`                                                          // Documentation URL
	Capabilities                      *AgentCapabilities     `protobuf:"bytes,10,opt,name=capabilities,proto3" json:"capabilities,omitempty"`                                                                                         // Supported A2A features
	Skills                            []*AgentSkill          `protobuf:"bytes,11,rep,name=skills,proto3" json:"skills,omitempty"`                                                                                                     // Agent skills/capabilities
	SupportsAuthenticatedExtendedCard bool                   `protobuf:"varint,12,opt,name=supports_authenticated_extended_card,json=supportsAuthenticatedExtendedCard,proto3" json:"supports_authenticated_extended_card,omitempty"` // Extended card support
	IconUrl                           string                 `protobuf:"bytes,13,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`                                                                                    // Optional icon URL
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *AgentCard) Reset() {
	*x = AgentCard{}
	mi := &file_proto_a2a_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCard) ProtoMessage() {}

func (x *AgentCard) ProtoReflect() protoreflect.Message {
	mi := &file_proto_a2a_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCard.ProtoReflect.Descriptor instead.
func (*AgentCard) Descriptor() ([]byte, []int) {
	return file_proto_a2a_core_proto_rawDescGZIP(), []int{7}
}

func (x *AgentCard) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *AgentCard) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentCard) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AgentCard) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AgentCard) GetPreferredTransport() string {
	if x != nil {
		return x.PreferredTransport
	}
	return ""
}

func (x *AgentCard) GetAdditionalInterfaces() []*AgentInterface {
	if x != nil {
		return x.AdditionalInterfaces
	}
	return nil
}

func (x *AgentCard) GetProvider() *AgentProvider {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *AgentCard) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentCard) GetDocumentationUrl() string {
	if x != nil {
		return x.DocumentationUrl
	}
	return ""
}

func (x *AgentCard) GetCapabilities() *AgentCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AgentCard) GetSkills() []*AgentSkill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *AgentCard) GetSupportsAuthenticatedExtendedCard() bool {
	if x != nil {
		return x.SupportsAuthenticatedExtendedCard
	}
	return false
}

func (x *AgentCard) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

// Agent provider information
type AgentProvider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`                   // Provider URL
	Organization  string                 `protobuf:"bytes,2,opt,name=organization,proto3" json:"organization,omitempty"` // Organization name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentProvider) Reset() {
	*x = AgentProvider{}
	mi := &file_proto_a2a_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentProvider) ProtoMessage() {}

func (x *AgentProvider) ProtoReflect() protoreflect.Message {
	mi := &file_proto_a2a_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentProvider.ProtoReflect.Descriptor instead.
func (*AgentProvider) Descriptor() ([]byte, []int) {
	return file_proto_a2a_core_proto_rawDescGZIP(), []int{8}
}

func (x *AgentProvider) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AgentProvider) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

// Agent capabilities declaration
type AgentCapabilities struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Streaming         bool                   `protobuf:"varint,1,opt,name=streaming,proto3" json:"streaming,omitempty"`                                          // Supports streaming responses
	PushNotifications bool                   `protobuf:"varint,2,opt,name=push_notifications,json=pushNotifications,proto3" json:"push_notifications,omitempty"` // Supports push notifications
	Extensions        []*AgentExtension      `protobuf:"bytes,3,rep,name=extensions,proto3" json:"extensions,omitempty"`                                         // Supported extensions
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AgentCapabilities) Reset() {
	*x = AgentCapabilities{}
	mi := &file_proto_a2a_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCapabilities) ProtoMessage() {}

func (x *AgentCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_proto_a2a_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCapabilities.ProtoReflect.Descriptor instead.
func (*AgentCapabilities) Descriptor() ([]byte, []int) {
	return file_proto_a2a_core_proto_rawDescGZIP(), []int{9}
}

func (x *AgentCapabilities) GetStreaming() bool {
	if x != nil {
		return x.Streaming
	}
	return false
}

func (x *AgentCapabilities) GetPushNotifications() bool {
	if x != nil {
		return x.PushNotifications
	}
	return false
}

func (x *AgentCapabilities) GetExtensions() []*AgentExtension {
	if x != nil {
		return x.Extensions
	}
	return nil
}

// Agent extension declaration
type AgentExtension struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`                 // Extension URI
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // Extension description
	Required      bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`      // Whether extension is required
	Params        *structpb.Struct       `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`           // Optional extension configuration
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentExtension) Reset() {
	*x = AgentExtension{}
	mi := &file_proto_a2a_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentExtension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentExtension) ProtoMessage() {}

func (x *AgentExtension) ProtoReflect() protoreflect.Message {
	mi := &file_proto_a2a_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentExtension.ProtoReflect.Descriptor instead.
func (*AgentExtension) Descriptor() ([]byte, []int) {
	return file_proto_a2a_core_proto_rawDescGZIP(), []int{10}
}

func (x *AgentExtension) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *AgentExtension) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AgentExtension) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *AgentExtension) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

// Agent skill/capability description
type AgentSkill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                      // Unique skill identifier
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                  // Human readable skill name
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                    // Skill description
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`                                  // Categorization tags
	Examples      []string               `protobuf:"bytes,5,rep,name=examples,proto3" json:"examples,omitempty"`                          // Example queries/requests
	InputModes    []string               `protobuf:"bytes,6,rep,name=input_modes,json=inputModes,proto3" json:"input_modes,omitempty"`    // Supported input MIME types
	OutputModes   []string               `protobuf:"bytes,7,rep,name=output_modes,json=outputModes,proto3" json:"output_modes,omitempty"` // Supported output MIME types
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSkill) Reset() {
	*x = AgentSkill{}
	mi := &file_proto_a2a_core_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSkill) ProtoMessage() {}

func (x *AgentSkill) ProtoReflect() protoreflect.Message {
	mi := &file_proto_a2a_core_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSkill.ProtoReflect.Descriptor instead.
func (*AgentSkill) Descriptor() ([]byte, []int) {
	return file_proto_a2a_core_proto_rawDescGZIP(), []int{11}
}

func (x *AgentSkill) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentSkill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentSkill) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AgentSkill) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *AgentSkill) GetExamples() []string {
	if x != nil {
		return x.Examples
	}
	return nil
}

func (x *AgentSkill) GetInputModes() []string {
	if x != nil {
		return x.InputModes
	}
	return nil
}

func (x *AgentSkill) GetOutputModes() []string {
	if x != nil {
		return x.OutputModes
	}
	return nil
}

// Agent interface for multiple transport support
type AgentInterface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`             // Interface URL
	Transport     string                 `protobuf:"bytes,2,opt,name=transport,proto3" json:"transport,omitempty"` // Transport protocol (JSONRPC, GRPC, HTTP+JSON)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInterface) Reset() {
	*x = AgentInterface{}
	mi := &file_proto_a2a_core_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInterface) ProtoMessage() {}

func (x *AgentInterface) ProtoReflect() protoreflect.Message {
	mi := &file_proto_a2a_core_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInterface.ProtoReflect.Descriptor instead.
func (*AgentInterface) Descriptor() ([]byte, []int) {
	return file_proto_a2a_core_proto_rawDescGZIP(), []int{12}
}

func (x *AgentInterface) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AgentInterface) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

var File_proto_a2a_core_proto protoreflect.FileDescriptor

const file_proto_a2a_core_proto_rawDesc = "" +
	"\n" +
	"\x14proto/a2a_core.proto\x12\x03a2a\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xa3\x01\n" +
	"\x04Part\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x12#\n" +
	"\x04file\x18\x02 \x01(\v2\r.a2a.FilePartH\x00R\x04file\x12#\n" +
	"\x04data\x18\x03 \x01(\v2\r.a2a.DataPartH\x00R\x04data\x123\n" +
	"\bmetadata\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bmetadataB\x06\n" +
	"\x04part\"\x93\x01\n" +
	"\bFilePart\x12$\n" +
	"\rfile_with_uri\x18\x01 \x01(\tH\x00R\vfileWithUri\x12(\n" +
	"\x0ffile_with_bytes\x18\x02 \x01(\fH\x00R\rfileWithBytes\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04nameB\x06\n" +
	"\x04file\"7\n" +
	"\bDataPart\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04data\"\xf9\x01\n" +
	"\aMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1d\n" +
	"\n" +
	"context_id\x18\x02 \x01(\tR\tcontextId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12\x1d\n" +
	"\x04role\x18\x04 \x01(\x0e2\t.a2a.RoleR\x04role\x12#\n" +
	"\acontent\x18\x05 \x03(\v2\t.a2a.PartR\acontent\x123\n" +
	"\bmetadata\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\x1e\n" +
	"\n" +
	"extensions\x18\a \x03(\tR\n" +
	"extensions\"\x92\x01\n" +
	"\n" +
	"TaskStatus\x12$\n" +
	"\x05state\x18\x01 \x01(\x0e2\x0e.a2a.TaskStateR\x05state\x12$\n" +
	"\x06update\x18\x02 \x01(\v2\f.a2a.MessageR\x06update\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xe8\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"context_id\x18\x02 \x01(\tR\tcontextId\x12'\n" +
	"\x06status\x18\x03 \x01(\v2\x0f.a2a.TaskStatusR\x06status\x12+\n" +
	"\tartifacts\x18\x04 \x03(\v2\r.a2a.ArtifactR\tartifacts\x12&\n" +
	"\ahistory\x18\x05 \x03(\v2\f.a2a.MessageR\ahistory\x123\n" +
	"\bmetadata\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\xd7\x01\n" +
	"\bArtifact\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1f\n" +
	"\x05parts\x18\x05 \x03(\v2\t.a2a.PartR\x05parts\x123\n" +
	"\bmetadata\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\x1e\n" +
	"\n" +
	"extensions\x18\a \x03(\tR\n" +
	"extensions\"\xc1\x04\n" +
	"\tAgentCard\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12/\n" +
	"\x13preferred_transport\x18\x05 \x01(\tR\x12preferredTransport\x12H\n" +
	"\x15additional_interfaces\x18\x06 \x03(\v2\x13.a2a.AgentInterfaceR\x14additionalInterfaces\x12.\n" +
	"\bprovider\x18\a \x01(\v2\x12.a2a.AgentProviderR\bprovider\x12\x18\n" +
	"\aversion\x18\b \x01(\tR\aversion\x12+\n" +
	"\x11documentation_url\x18\t \x01(\tR\x10documentationUrl\x12:\n" +
	"\fcapabilities\x18\n" +
	" \x01(\v2\x16.a2a.AgentCapabilitiesR\fcapabilities\x12'\n" +
	"\x06skills\x18\v \x03(\v2\x0f.a2a.AgentSkillR\x06skills\x12O\n" +
	"$supports_authenticated_extended_card\x18\f \x01(\bR!supportsAuthenticatedExtendedCard\x12\x19\n" +
	"\bicon_url\x18\r \x01(\tR\aiconUrl\"E\n" +
	"\rAgentProvider\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\"\n" +
	"\forganization\x18\x02 \x01(\tR\forganization\"\x95\x01\n" +
	"\x11AgentCapabilities\x12\x1c\n" +
	"\tstreaming\x18\x01 \x01(\bR\tstreaming\x12-\n" +
	"\x12push_notifications\x18\x02 \x01(\bR\x11pushNotifications\x123\n" +
	"\n" +
	"extensions\x18\x03 \x03(\v2\x13.a2a.AgentExtensionR\n" +
	"extensions\"\x91\x01\n" +
	"\x0eAgentExtension\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12/\n" +
	"\x06params\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06params\"\xc6\x01\n" +
	"\n" +
	"AgentSkill\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x1a\n" +
	"\bexamples\x18\x05 \x03(\tR\bexamples\x12\x1f\n" +
	"\vinput_modes\x18\x06 \x03(\tR\n" +
	"inputModes\x12!\n" +
	"\foutput_modes\x18\a \x03(\tR\voutputModes\"@\n" +
	"\x0eAgentInterface\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1c\n" +
	"\ttransport\x18\x02 \x01(\tR\ttransport*;\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tROLE_USER\x10\x01\x12\x0e\n" +
	"\n" +
	"ROLE_AGENT\x10\x02*\xfa\x01\n" +
	"\tTaskState\x12\x1a\n" +
	"\x16TASK_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TASK_STATE_SUBMITTED\x10\x01\x12\x16\n" +
	"\x12TASK_STATE_WORKING\x10\x02\x12\x18\n" +
	"\x14TASK_STATE_COMPLETED\x10\x03\x12\x15\n" +
	"\x11TASK_STATE_FAILED\x10\x04\x12\x18\n" +
	"\x14TASK_STATE_CANCELLED\x10\x05\x12\x1d\n" +
	"\x19TASK_STATE_INPUT_REQUIRED\x10\x06\x12\x17\n" +
	"\x13TASK_STATE_REJECTED\x10\a\x12\x1c\n" +
	"\x18TASK_STATE_AUTH_REQUIRED\x10\bB\x10Z\x0eevents/a2a;a2ab\x06proto3"

var (
	file_proto_a2a_core_proto_rawDescOnce sync.Once
	file_proto_a2a_core_proto_rawDescData []byte
)

func file_proto_a2a_core_proto_rawDescGZIP() []byte {
	file_proto_a2a_core_proto_rawDescOnce.Do(func() {
		file_proto_a2a_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_a2a_core_proto_rawDesc), len(file_proto_a2a_core_proto_rawDesc)))
	})
	return file_proto_a2a_core_proto_rawDescData
}

var file_proto_a2a_core_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_a2a_core_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_a2a_core_proto_goTypes = []any{
	(Role)(0),                     // 0: a2a.Role
	(TaskState)(0),                // 1: a2a.TaskState
	(*Part)(nil),                  // 2: a2a.Part
	(*FilePart)(nil),              // 3: a2a.FilePart
	(*DataPart)(nil),              // 4: a2a.DataPart
	(*Message)(nil),               // 5: a2a.Message
	(*TaskStatus)(nil),            // 6: a2a.TaskStatus
	(*Task)(nil),                  // 7: a2a.Task
	(*Artifact)(nil),              // 8: a2a.Artifact
	(*AgentCard)(nil),             // 9: a2a.AgentCard
	(*AgentProvider)(nil),         // 10: a2a.AgentProvider
	(*AgentCapabilities)(nil),     // 11: a2a.AgentCapabilities
	(*AgentExtension)(nil),        // 12: a2a.AgentExtension
	(*AgentSkill)(nil),            // 13: a2a.AgentSkill
	(*AgentInterface)(nil),        // 14: a2a.AgentInterface
	(*structpb.Struct)(nil),       // 15: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
}
var file_proto_a2a_core_proto_depIdxs = []int32{
	3,  // 0: a2a.Part.file:type_name -> a2a.FilePart
	4,  // 1: a2a.Part.data:type_name -> a2a.DataPart
	15, // 2: a2a.Part.metadata:type_name -> google.protobuf.Struct
	15, // 3: a2a.DataPart.data:type_name -> google.protobuf.Struct
	0,  // 4: a2a.Message.role:type_name -> a2a.Role
	2,  // 5: a2a.Message.content:type_name -> a2a.Part
	15, // 6: a2a.Message.metadata:type_name -> google.protobuf.Struct
	1,  // 7: a2a.TaskStatus.state:type_name -> a2a.TaskState
	5,  // 8: a2a.TaskStatus.update:type_name -> a2a.Message
	16, // 9: a2a.TaskStatus.timestamp:type_name -> google.protobuf.Timestamp
	6,  // 10: a2a.Task.status:type_name -> a2a.TaskStatus
	8,  // 11: a2a.Task.artifacts:type_name -> a2a.Artifact
	5,  // 12: a2a.Task.history:type_name -> a2a.Message
	15, // 13: a2a.Task.metadata:type_name -> google.protobuf.Struct
	2,  // 14: a2a.Artifact.parts:type_name -> a2a.Part
	15, // 15: a2a.Artifact.metadata:type_name -> google.protobuf.Struct
	14, // 16: a2a.AgentCard.additional_interfaces:type_name -> a2a.AgentInterface
	10, // 17: a2a.AgentCard.provider:type_name -> a2a.AgentProvider
	11, // 18: a2a.AgentCard.capabilities:type_name -> a2a.AgentCapabilities
	13, // 19: a2a.AgentCard.skills:type_name -> a2a.AgentSkill
	12, // 20: a2a.AgentCapabilities.extensions:type_name -> a2a.AgentExtension
	15, // 21: a2a.AgentExtension.params:type_name -> google.protobuf.Struct
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_proto_a2a_core_proto_init() }
func file_proto_a2a_core_proto_init() {
	if File_proto_a2a_core_proto != nil {
		return
	}
	file_proto_a2a_core_proto_msgTypes[0].OneofWrappers = []any{
		(*Part_Text)(nil),
		(*Part_File)(nil),
		(*Part_Data)(nil),
	}
	file_proto_a2a_core_proto_msgTypes[1].OneofWrappers = []any{
		(*FilePart_FileWithUri)(nil),
		(*FilePart_FileWithBytes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_a2a_core_proto_rawDesc), len(file_proto_a2a_core_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_a2a_core_proto_goTypes,
		DependencyIndexes: file_proto_a2a_core_proto_depIdxs,
		EnumInfos:         file_proto_a2a_core_proto_enumTypes,
		MessageInfos:      file_proto_a2a_core_proto_msgTypes,
	}.Build()
	File_proto_a2a_core_proto = out.File
	file_proto_a2a_core_proto_goTypes = nil
	file_proto_a2a_core_proto_depIdxs = nil
}
