// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/eventbus.proto

package a2a

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Priority levels for event processing and delivery ordering.
// Higher priority events are processed before lower priority ones in queues.
type Priority int32

const (
	Priority_PRIORITY_UNSPECIFIED Priority = 0 // Default priority (treated as MEDIUM)
	Priority_PRIORITY_LOW         Priority = 1 // Background tasks, cleanup, telemetry
	Priority_PRIORITY_MEDIUM      Priority = 2 // Normal agent-to-agent communication
	Priority_PRIORITY_HIGH        Priority = 3 // Urgent tasks, real-time responses
	Priority_PRIORITY_CRITICAL    Priority = 4 // System alerts, error conditions
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "PRIORITY_LOW",
		2: "PRIORITY_MEDIUM",
		3: "PRIORITY_HIGH",
		4: "PRIORITY_CRITICAL",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"PRIORITY_LOW":         1,
		"PRIORITY_MEDIUM":      2,
		"PRIORITY_HIGH":        3,
		"PRIORITY_CRITICAL":    4,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_eventbus_proto_enumTypes[0].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_proto_eventbus_proto_enumTypes[0]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_proto_eventbus_proto_rawDescGZIP(), []int{0}
}

// AgentEvent wraps A2A messages for transport through the EDA broker.
// This allows A2A messages to be routed, queued, and delivered using
// event-driven patterns while maintaining A2A protocol compliance.
type AgentEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EventId   string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"` // Unique identifier for this event (for deduplication and tracking)
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`            // When this event was created (for ordering and TTL)
	// A2A-compliant payload - exactly one of these must be set
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentEvent_Message
	//	*AgentEvent_Task
	//	*AgentEvent_StatusUpdate
	//	*AgentEvent_ArtifactUpdate
	//	*AgentEvent_AgentCard
	Payload isAgentEvent_Payload `protobuf_oneof:"payload"`
	// EDA routing metadata for event distribution
	Routing *AgentEventMetadata `protobuf:"bytes,20,opt,name=routing,proto3" json:"routing,omitempty"`
	// OpenTelemetry distributed tracing context
	TraceId       string `protobuf:"bytes,30,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"` // Trace ID for request correlation
	SpanId        string `protobuf:"bytes,31,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`    // Span ID for operation tracking
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_proto_eventbus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventbus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_proto_eventbus_proto_rawDescGZIP(), []int{0}
}

func (x *AgentEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AgentEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AgentEvent) GetPayload() isAgentEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentEvent) GetMessage() *Message {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *AgentEvent) GetTask() *Task {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_Task); ok {
			return x.Task
		}
	}
	return nil
}

func (x *AgentEvent) GetStatusUpdate() *TaskStatusUpdateEvent {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_StatusUpdate); ok {
			return x.StatusUpdate
		}
	}
	return nil
}

func (x *AgentEvent) GetArtifactUpdate() *TaskArtifactUpdateEvent {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_ArtifactUpdate); ok {
			return x.ArtifactUpdate
		}
	}
	return nil
}

func (x *AgentEvent) GetAgentCard() *AgentCardEvent {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_AgentCard); ok {
			return x.AgentCard
		}
	}
	return nil
}

func (x *AgentEvent) GetRouting() *AgentEventMetadata {
	if x != nil {
		return x.Routing
	}
	return nil
}

func (x *AgentEvent) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *AgentEvent) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

type isAgentEvent_Payload interface {
	isAgentEvent_Payload()
}

type AgentEvent_Message struct {
	Message *Message `protobuf:"bytes,10,opt,name=message,proto3,oneof"` // A2A Message for agent communication
}

type AgentEvent_Task struct {
	Task *Task `protobuf:"bytes,11,opt,name=task,proto3,oneof"` // A2A Task for work coordination
}

type AgentEvent_StatusUpdate struct {
	StatusUpdate *TaskStatusUpdateEvent `protobuf:"bytes,12,opt,name=status_update,json=statusUpdate,proto3,oneof"` // Task lifecycle state changes
}

type AgentEvent_ArtifactUpdate struct {
	ArtifactUpdate *TaskArtifactUpdateEvent `protobuf:"bytes,13,opt,name=artifact_update,json=artifactUpdate,proto3,oneof"` // Task output artifacts
}

type AgentEvent_AgentCard struct {
	AgentCard *AgentCardEvent `protobuf:"bytes,14,opt,name=agent_card,json=agentCard,proto3,oneof"` // Agent registration/discovery event
}

func (*AgentEvent_Message) isAgentEvent_Payload() {}

func (*AgentEvent_Task) isAgentEvent_Payload() {}

func (*AgentEvent_StatusUpdate) isAgentEvent_Payload() {}

func (*AgentEvent_ArtifactUpdate) isAgentEvent_Payload() {}

func (*AgentEvent_AgentCard) isAgentEvent_Payload() {}

// AgentEventMetadata provides routing and delivery information for events.
// This enables sophisticated event routing patterns including point-to-point,
// broadcast, topic-based, and priority-based delivery.
type AgentEventMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAgentId   string                 `protobuf:"bytes,1,opt,name=from_agent_id,json=fromAgentId,proto3" json:"from_agent_id,omitempty"` // Source agent identifier (for reply routing)
	ToAgentId     string                 `protobuf:"bytes,2,opt,name=to_agent_id,json=toAgentId,proto3" json:"to_agent_id,omitempty"`       // Target agent ID (empty string means broadcast to all)
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`         // Event classification ("message", "task", "status_update", "artifact")
	Subscriptions []string               `protobuf:"bytes,4,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`                  // Topic-based routing tags for content-based filtering
	Priority      Priority               `protobuf:"varint,5,opt,name=priority,proto3,enum=agenthub.Priority" json:"priority,omitempty"`    // Delivery priority for event queue ordering
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEventMetadata) Reset() {
	*x = AgentEventMetadata{}
	mi := &file_proto_eventbus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEventMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEventMetadata) ProtoMessage() {}

func (x *AgentEventMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventbus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEventMetadata.ProtoReflect.Descriptor instead.
func (*AgentEventMetadata) Descriptor() ([]byte, []int) {
	return file_proto_eventbus_proto_rawDescGZIP(), []int{1}
}

func (x *AgentEventMetadata) GetFromAgentId() string {
	if x != nil {
		return x.FromAgentId
	}
	return ""
}

func (x *AgentEventMetadata) GetToAgentId() string {
	if x != nil {
		return x.ToAgentId
	}
	return ""
}

func (x *AgentEventMetadata) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AgentEventMetadata) GetSubscriptions() []string {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *AgentEventMetadata) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

// TaskStatusUpdateEvent notifies subscribers about A2A task lifecycle changes.
// This event is published whenever a task transitions between states
// (SUBMITTED → WORKING → COMPLETED/FAILED/CANCELLED).
type TaskStatusUpdateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`          // A2A task identifier
	ContextId     string                 `protobuf:"bytes,2,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"` // A2A conversation context
	Status        *TaskStatus            `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                        // New A2A task status with state and update message
	Final         bool                   `protobuf:"varint,4,opt,name=final,proto3" json:"final,omitempty"`                         // True if this is the terminal state for the task
	Metadata      *structpb.Struct       `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`                    // Additional event metadata (timing, agent info, etc.)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusUpdateEvent) Reset() {
	*x = TaskStatusUpdateEvent{}
	mi := &file_proto_eventbus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusUpdateEvent) ProtoMessage() {}

func (x *TaskStatusUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventbus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusUpdateEvent.ProtoReflect.Descriptor instead.
func (*TaskStatusUpdateEvent) Descriptor() ([]byte, []int) {
	return file_proto_eventbus_proto_rawDescGZIP(), []int{2}
}

func (x *TaskStatusUpdateEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskStatusUpdateEvent) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *TaskStatusUpdateEvent) GetStatus() *TaskStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *TaskStatusUpdateEvent) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

func (x *TaskStatusUpdateEvent) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// TaskArtifactUpdateEvent delivers A2A task output artifacts to subscribers.
// Supports both atomic artifact delivery and streaming for large outputs.
type TaskArtifactUpdateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`           // A2A task that produced this artifact
	ContextId     string                 `protobuf:"bytes,2,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`  // A2A conversation context
	Artifact      *Artifact              `protobuf:"bytes,3,opt,name=artifact,proto3" json:"artifact,omitempty"`                     // The A2A artifact containing structured output
	Append        bool                   `protobuf:"varint,4,opt,name=append,proto3" json:"append,omitempty"`                        // True to append to existing artifact, false to replace
	LastChunk     bool                   `protobuf:"varint,5,opt,name=last_chunk,json=lastChunk,proto3" json:"last_chunk,omitempty"` // True if this completes a streaming artifact
	Metadata      *structpb.Struct       `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`                     // Delivery metadata (chunk info, compression, etc.)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskArtifactUpdateEvent) Reset() {
	*x = TaskArtifactUpdateEvent{}
	mi := &file_proto_eventbus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskArtifactUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskArtifactUpdateEvent) ProtoMessage() {}

func (x *TaskArtifactUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventbus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskArtifactUpdateEvent.ProtoReflect.Descriptor instead.
func (*TaskArtifactUpdateEvent) Descriptor() ([]byte, []int) {
	return file_proto_eventbus_proto_rawDescGZIP(), []int{3}
}

func (x *TaskArtifactUpdateEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskArtifactUpdateEvent) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *TaskArtifactUpdateEvent) GetArtifact() *Artifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *TaskArtifactUpdateEvent) GetAppend() bool {
	if x != nil {
		return x.Append
	}
	return false
}

func (x *TaskArtifactUpdateEvent) GetLastChunk() bool {
	if x != nil {
		return x.LastChunk
	}
	return false
}

func (x *TaskArtifactUpdateEvent) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// AgentCardEvent notifies subscribers about agent registration and capability updates.
// This event is published when an agent registers or updates its capabilities.
type AgentCardEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`       // Unique agent identifier
	AgentCard     *AgentCard             `protobuf:"bytes,2,opt,name=agent_card,json=agentCard,proto3" json:"agent_card,omitempty"` // The agent's A2A card with capabilities
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // Event type: "registered", "updated", "unregistered"
	Metadata      *structpb.Struct       `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`                    // Additional metadata (registration time, etc.)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCardEvent) Reset() {
	*x = AgentCardEvent{}
	mi := &file_proto_eventbus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCardEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCardEvent) ProtoMessage() {}

func (x *AgentCardEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventbus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCardEvent.ProtoReflect.Descriptor instead.
func (*AgentCardEvent) Descriptor() ([]byte, []int) {
	return file_proto_eventbus_proto_rawDescGZIP(), []int{4}
}

func (x *AgentCardEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentCardEvent) GetAgentCard() *AgentCard {
	if x != nil {
		return x.AgentCard
	}
	return nil
}

func (x *AgentCardEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AgentCardEvent) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type PublishMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // A2A message
	Routing       *AgentEventMetadata    `protobuf:"bytes,2,opt,name=routing,proto3" json:"routing,omitempty"` // EDA routing info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishMessageRequest) Reset() {
	*x = PublishMessageRequest{}
	mi := &file_proto_eventbus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishMessageRequest) ProtoMessage() {}

func (x *PublishMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventbus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishMessageRequest.ProtoReflect.Descriptor instead.
func (*PublishMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_eventbus_proto_rawDescGZIP(), []int{5}
}

func (x *PublishMessageRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *PublishMessageRequest) GetRouting() *AgentEventMetadata {
	if x != nil {
		return x.Routing
	}
	return nil
}

type PublishTaskUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Update        *TaskStatusUpdateEvent `protobuf:"bytes,1,opt,name=update,proto3" json:"update,omitempty"`
	Routing       *AgentEventMetadata    `protobuf:"bytes,2,opt,name=routing,proto3" json:"routing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishTaskUpdateRequest) Reset() {
	*x = PublishTaskUpdateRequest{}
	mi := &file_proto_eventbus_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishTaskUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishTaskUpdateRequest) ProtoMessage() {}

func (x *PublishTaskUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventbus_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishTaskUpdateRequest.ProtoReflect.Descriptor instead.
func (*PublishTaskUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_eventbus_proto_rawDescGZIP(), []int{6}
}

func (x *PublishTaskUpdateRequest) GetUpdate() *TaskStatusUpdateEvent {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *PublishTaskUpdateRequest) GetRouting() *AgentEventMetadata {
	if x != nil {
		return x.Routing
	}
	return nil
}

type PublishTaskArtifactRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Artifact      *TaskArtifactUpdateEvent `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	Routing       *AgentEventMetadata      `protobuf:"bytes,2,opt,name=routing,proto3" json:"routing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishTaskArtifactRequest) Reset() {
	*x = PublishTaskArtifactRequest{}
	mi := &file_proto_eventbus_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishTaskArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishTaskArtifactRequest) ProtoMessage() {}

func (x *PublishTaskArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventbus_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishTaskArtifactRequest.ProtoReflect.Descriptor instead.
func (*PublishTaskArtifactRequest) Descriptor() ([]byte, []int) {
	return file_proto_eventbus_proto_rawDescGZIP(), []int{7}
}

func (x *PublishTaskArtifactRequest) GetArtifact() *TaskArtifactUpdateEvent {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *PublishTaskArtifactRequest) GetRouting() *AgentEventMetadata {
	if x != nil {
		return x.Routing
	}
	return nil
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	EventId       string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"` // Generated event ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_proto_eventbus_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventbus_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_proto_eventbus_proto_rawDescGZIP(), []int{8}
}

func (x *PublishResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PublishResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PublishResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type SubscribeToMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                // Subscribe for this agent
	MessageTypes  []string               `protobuf:"bytes,2,rep,name=message_types,json=messageTypes,proto3" json:"message_types,omitempty"` // Optional filter
	Contexts      []string               `protobuf:"bytes,3,rep,name=contexts,proto3" json:"contexts,omitempty"`                             // Optional context filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeToMessagesRequest) Reset() {
	*x = SubscribeToMessagesRequest{}
	mi := &file_proto_eventbus_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeToMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeToMessagesRequest) ProtoMessage() {}

func (x *SubscribeToMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventbus_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeToMessagesRequest.ProtoReflect.Descriptor instead.
func (*SubscribeToMessagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_eventbus_proto_rawDescGZIP(), []int{9}
}

func (x *SubscribeToMessagesRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SubscribeToMessagesRequest) GetMessageTypes() []string {
	if x != nil {
		return x.MessageTypes
	}
	return nil
}

func (x *SubscribeToMessagesRequest) GetContexts() []string {
	if x != nil {
		return x.Contexts
	}
	return nil
}

type SubscribeToTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`           // Subscribe for this agent
	TaskTypes     []string               `protobuf:"bytes,2,rep,name=task_types,json=taskTypes,proto3" json:"task_types,omitempty"`     // Optional filter
	States        []TaskState            `protobuf:"varint,3,rep,packed,name=states,proto3,enum=a2a.TaskState" json:"states,omitempty"` // Optional state filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeToTasksRequest) Reset() {
	*x = SubscribeToTasksRequest{}
	mi := &file_proto_eventbus_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeToTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeToTasksRequest) ProtoMessage() {}

func (x *SubscribeToTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventbus_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeToTasksRequest.ProtoReflect.Descriptor instead.
func (*SubscribeToTasksRequest) Descriptor() ([]byte, []int) {
	return file_proto_eventbus_proto_rawDescGZIP(), []int{10}
}

func (x *SubscribeToTasksRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SubscribeToTasksRequest) GetTaskTypes() []string {
	if x != nil {
		return x.TaskTypes
	}
	return nil
}

func (x *SubscribeToTasksRequest) GetStates() []TaskState {
	if x != nil {
		return x.States
	}
	return nil
}

type SubscribeToAgentEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`          // Subscribe for this agent
	EventTypes    []string               `protobuf:"bytes,2,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"` // Optional event type filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeToAgentEventsRequest) Reset() {
	*x = SubscribeToAgentEventsRequest{}
	mi := &file_proto_eventbus_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeToAgentEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeToAgentEventsRequest) ProtoMessage() {}

func (x *SubscribeToAgentEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventbus_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeToAgentEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeToAgentEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_eventbus_proto_rawDescGZIP(), []int{11}
}

func (x *SubscribeToAgentEventsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SubscribeToAgentEventsRequest) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	HistoryLength int32                  `protobuf:"varint,2,opt,name=history_length,json=historyLength,proto3" json:"history_length,omitempty"` // How much history to include
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_proto_eventbus_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventbus_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_eventbus_proto_rawDescGZIP(), []int{12}
}

func (x *GetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetTaskRequest) GetHistoryLength() int32 {
	if x != nil {
		return x.HistoryLength
	}
	return 0
}

type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // Optional cancellation reason
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_proto_eventbus_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventbus_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_eventbus_proto_rawDescGZIP(), []int{13}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CancelTaskRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`           // Tasks for this agent
	ContextId     string                 `protobuf:"bytes,2,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`     // Optional context filter
	States        []TaskState            `protobuf:"varint,3,rep,packed,name=states,proto3,enum=a2a.TaskState" json:"states,omitempty"` // Optional state filter
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_proto_eventbus_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventbus_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_proto_eventbus_proto_rawDescGZIP(), []int{14}
}

func (x *ListTasksRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ListTasksRequest) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *ListTasksRequest) GetStates() []TaskState {
	if x != nil {
		return x.States
	}
	return nil
}

func (x *ListTasksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTasksRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_proto_eventbus_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventbus_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_proto_eventbus_proto_rawDescGZIP(), []int{15}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type RegisterAgentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentCard      *AgentCard             `protobuf:"bytes,1,opt,name=agent_card,json=agentCard,proto3" json:"agent_card,omitempty"`                  // Agent's A2A card
	Subscriptions  []string               `protobuf:"bytes,2,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`                           // Event subscriptions
	HealthCheckUrl string                 `protobuf:"bytes,3,opt,name=health_check_url,json=healthCheckUrl,proto3" json:"health_check_url,omitempty"` // Optional health check endpoint
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_proto_eventbus_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventbus_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_eventbus_proto_rawDescGZIP(), []int{16}
}

func (x *RegisterAgentRequest) GetAgentCard() *AgentCard {
	if x != nil {
		return x.AgentCard
	}
	return nil
}

func (x *RegisterAgentRequest) GetSubscriptions() []string {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *RegisterAgentRequest) GetHealthCheckUrl() string {
	if x != nil {
		return x.HealthCheckUrl
	}
	return ""
}

type RegisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // Assigned/confirmed agent ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_proto_eventbus_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventbus_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_eventbus_proto_rawDescGZIP(), []int{17}
}

func (x *RegisterAgentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterAgentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RegisterAgentResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// DEPRECATED: Use a2a.Task instead
//
// Deprecated: Marked as deprecated in proto/eventbus.proto.
type TaskMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TaskId           string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskType         string                 `protobuf:"bytes,2,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Parameters       *structpb.Struct       `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"`
	RequesterAgentId string                 `protobuf:"bytes,4,opt,name=requester_agent_id,json=requesterAgentId,proto3" json:"requester_agent_id,omitempty"`
	ResponderAgentId string                 `protobuf:"bytes,5,opt,name=responder_agent_id,json=responderAgentId,proto3" json:"responder_agent_id,omitempty"`
	Deadline         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Priority         Priority               `protobuf:"varint,7,opt,name=priority,proto3,enum=agenthub.Priority" json:"priority,omitempty"`
	Metadata         *structpb.Struct       `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TaskMessage) Reset() {
	*x = TaskMessage{}
	mi := &file_proto_eventbus_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskMessage) ProtoMessage() {}

func (x *TaskMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventbus_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskMessage.ProtoReflect.Descriptor instead.
func (*TaskMessage) Descriptor() ([]byte, []int) {
	return file_proto_eventbus_proto_rawDescGZIP(), []int{18}
}

func (x *TaskMessage) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskMessage) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *TaskMessage) GetParameters() *structpb.Struct {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *TaskMessage) GetRequesterAgentId() string {
	if x != nil {
		return x.RequesterAgentId
	}
	return ""
}

func (x *TaskMessage) GetResponderAgentId() string {
	if x != nil {
		return x.ResponderAgentId
	}
	return ""
}

func (x *TaskMessage) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *TaskMessage) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *TaskMessage) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TaskMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// DEPRECATED: Use a2a.Task with appropriate status instead
//
// Deprecated: Marked as deprecated in proto/eventbus.proto.
type TaskResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TaskId            string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status            TaskState              `protobuf:"varint,2,opt,name=status,proto3,enum=a2a.TaskState" json:"status,omitempty"`
	Result            *structpb.Struct       `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	ErrorMessage      string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ExecutorAgentId   string                 `protobuf:"bytes,5,opt,name=executor_agent_id,json=executorAgentId,proto3" json:"executor_agent_id,omitempty"`
	CompletedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	ExecutionMetadata *structpb.Struct       `protobuf:"bytes,7,opt,name=execution_metadata,json=executionMetadata,proto3" json:"execution_metadata,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_proto_eventbus_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventbus_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_proto_eventbus_proto_rawDescGZIP(), []int{19}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetStatus() TaskState {
	if x != nil {
		return x.Status
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

func (x *TaskResult) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TaskResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskResult) GetExecutorAgentId() string {
	if x != nil {
		return x.ExecutorAgentId
	}
	return ""
}

func (x *TaskResult) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *TaskResult) GetExecutionMetadata() *structpb.Struct {
	if x != nil {
		return x.ExecutionMetadata
	}
	return nil
}

// DEPRECATED: Use TaskStatusUpdateEvent instead
//
// Deprecated: Marked as deprecated in proto/eventbus.proto.
type TaskProgress struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TaskId             string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status             TaskState              `protobuf:"varint,2,opt,name=status,proto3,enum=a2a.TaskState" json:"status,omitempty"`
	ProgressMessage    string                 `protobuf:"bytes,3,opt,name=progress_message,json=progressMessage,proto3" json:"progress_message,omitempty"`
	ProgressPercentage int32                  `protobuf:"varint,4,opt,name=progress_percentage,json=progressPercentage,proto3" json:"progress_percentage,omitempty"`
	ProgressData       *structpb.Struct       `protobuf:"bytes,5,opt,name=progress_data,json=progressData,proto3" json:"progress_data,omitempty"`
	ExecutorAgentId    string                 `protobuf:"bytes,6,opt,name=executor_agent_id,json=executorAgentId,proto3" json:"executor_agent_id,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TaskProgress) Reset() {
	*x = TaskProgress{}
	mi := &file_proto_eventbus_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskProgress) ProtoMessage() {}

func (x *TaskProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventbus_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskProgress.ProtoReflect.Descriptor instead.
func (*TaskProgress) Descriptor() ([]byte, []int) {
	return file_proto_eventbus_proto_rawDescGZIP(), []int{20}
}

func (x *TaskProgress) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskProgress) GetStatus() TaskState {
	if x != nil {
		return x.Status
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

func (x *TaskProgress) GetProgressMessage() string {
	if x != nil {
		return x.ProgressMessage
	}
	return ""
}

func (x *TaskProgress) GetProgressPercentage() int32 {
	if x != nil {
		return x.ProgressPercentage
	}
	return 0
}

func (x *TaskProgress) GetProgressData() *structpb.Struct {
	if x != nil {
		return x.ProgressData
	}
	return nil
}

func (x *TaskProgress) GetExecutorAgentId() string {
	if x != nil {
		return x.ExecutorAgentId
	}
	return ""
}

func (x *TaskProgress) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_proto_eventbus_proto protoreflect.FileDescriptor

const file_proto_eventbus_proto_rawDesc = "" +
	"\n" +
	"\x14proto/eventbus.proto\x12\bagenthub\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x14proto/a2a_core.proto\"\xf4\x03\n" +
	"\n" +
	"AgentEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12(\n" +
	"\amessage\x18\n" +
	" \x01(\v2\f.a2a.MessageH\x00R\amessage\x12\x1f\n" +
	"\x04task\x18\v \x01(\v2\t.a2a.TaskH\x00R\x04task\x12F\n" +
	"\rstatus_update\x18\f \x01(\v2\x1f.agenthub.TaskStatusUpdateEventH\x00R\fstatusUpdate\x12L\n" +
	"\x0fartifact_update\x18\r \x01(\v2!.agenthub.TaskArtifactUpdateEventH\x00R\x0eartifactUpdate\x129\n" +
	"\n" +
	"agent_card\x18\x0e \x01(\v2\x18.agenthub.AgentCardEventH\x00R\tagentCard\x126\n" +
	"\arouting\x18\x14 \x01(\v2\x1c.agenthub.AgentEventMetadataR\arouting\x12\x19\n" +
	"\btrace_id\x18\x1e \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x1f \x01(\tR\x06spanIdB\t\n" +
	"\apayload\"\xcd\x01\n" +
	"\x12AgentEventMetadata\x12\"\n" +
	"\rfrom_agent_id\x18\x01 \x01(\tR\vfromAgentId\x12\x1e\n" +
	"\vto_agent_id\x18\x02 \x01(\tR\ttoAgentId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12$\n" +
	"\rsubscriptions\x18\x04 \x03(\tR\rsubscriptions\x12.\n" +
	"\bpriority\x18\x05 \x01(\x0e2\x12.agenthub.PriorityR\bpriority\"\xc3\x01\n" +
	"\x15TaskStatusUpdateEvent\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"context_id\x18\x02 \x01(\tR\tcontextId\x12'\n" +
	"\x06status\x18\x03 \x01(\v2\x0f.a2a.TaskStatusR\x06status\x12\x14\n" +
	"\x05final\x18\x04 \x01(\bR\x05final\x123\n" +
	"\bmetadata\x18\x05 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\xe8\x01\n" +
	"\x17TaskArtifactUpdateEvent\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"context_id\x18\x02 \x01(\tR\tcontextId\x12)\n" +
	"\bartifact\x18\x03 \x01(\v2\r.a2a.ArtifactR\bartifact\x12\x16\n" +
	"\x06append\x18\x04 \x01(\bR\x06append\x12\x1d\n" +
	"\n" +
	"last_chunk\x18\x05 \x01(\bR\tlastChunk\x123\n" +
	"\bmetadata\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\xae\x01\n" +
	"\x0eAgentCardEvent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12-\n" +
	"\n" +
	"agent_card\x18\x02 \x01(\v2\x0e.a2a.AgentCardR\tagentCard\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x123\n" +
	"\bmetadata\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"w\n" +
	"\x15PublishMessageRequest\x12&\n" +
	"\amessage\x18\x01 \x01(\v2\f.a2a.MessageR\amessage\x126\n" +
	"\arouting\x18\x02 \x01(\v2\x1c.agenthub.AgentEventMetadataR\arouting\"\x8b\x01\n" +
	"\x18PublishTaskUpdateRequest\x127\n" +
	"\x06update\x18\x01 \x01(\v2\x1f.agenthub.TaskStatusUpdateEventR\x06update\x126\n" +
	"\arouting\x18\x02 \x01(\v2\x1c.agenthub.AgentEventMetadataR\arouting\"\x93\x01\n" +
	"\x1aPublishTaskArtifactRequest\x12=\n" +
	"\bartifact\x18\x01 \x01(\v2!.agenthub.TaskArtifactUpdateEventR\bartifact\x126\n" +
	"\arouting\x18\x02 \x01(\v2\x1c.agenthub.AgentEventMetadataR\arouting\"\\\n" +
	"\x0fPublishResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\"x\n" +
	"\x1aSubscribeToMessagesRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12#\n" +
	"\rmessage_types\x18\x02 \x03(\tR\fmessageTypes\x12\x1a\n" +
	"\bcontexts\x18\x03 \x03(\tR\bcontexts\"{\n" +
	"\x17SubscribeToTasksRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"task_types\x18\x02 \x03(\tR\ttaskTypes\x12&\n" +
	"\x06states\x18\x03 \x03(\x0e2\x0e.a2a.TaskStateR\x06states\"[\n" +
	"\x1dSubscribeToAgentEventsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1f\n" +
	"\vevent_types\x18\x02 \x03(\tR\n" +
	"eventTypes\"P\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12%\n" +
	"\x0ehistory_length\x18\x02 \x01(\x05R\rhistoryLength\"D\n" +
	"\x11CancelTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xb0\x01\n" +
	"\x10ListTasksRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"context_id\x18\x02 \x01(\tR\tcontextId\x12&\n" +
	"\x06states\x18\x03 \x03(\x0e2\x0e.a2a.TaskStateR\x06states\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\"\\\n" +
	"\x11ListTasksResponse\x12\x1f\n" +
	"\x05tasks\x18\x01 \x03(\v2\t.a2a.TaskR\x05tasks\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x95\x01\n" +
	"\x14RegisterAgentRequest\x12-\n" +
	"\n" +
	"agent_card\x18\x01 \x01(\v2\x0e.a2a.AgentCardR\tagentCard\x12$\n" +
	"\rsubscriptions\x18\x02 \x03(\tR\rsubscriptions\x12(\n" +
	"\x10health_check_url\x18\x03 \x01(\tR\x0ehealthCheckUrl\"b\n" +
	"\x15RegisterAgentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\"\xb4\x03\n" +
	"\vTaskMessage\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\ttask_type\x18\x02 \x01(\tR\btaskType\x127\n" +
	"\n" +
	"parameters\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"parameters\x12,\n" +
	"\x12requester_agent_id\x18\x04 \x01(\tR\x10requesterAgentId\x12,\n" +
	"\x12responder_agent_id\x18\x05 \x01(\tR\x10responderAgentId\x126\n" +
	"\bdeadline\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12.\n" +
	"\bpriority\x18\a \x01(\x0e2\x12.agenthub.PriorityR\bpriority\x123\n" +
	"\bmetadata\x18\b \x01(\v2\x17.google.protobuf.StructR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt:\x02\x18\x01\"\xda\x02\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12&\n" +
	"\x06status\x18\x02 \x01(\x0e2\x0e.a2a.TaskStateR\x06status\x12/\n" +
	"\x06result\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06result\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12*\n" +
	"\x11executor_agent_id\x18\x05 \x01(\tR\x0fexecutorAgentId\x12=\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12F\n" +
	"\x12execution_metadata\x18\a \x01(\v2\x17.google.protobuf.StructR\x11executionMetadata:\x02\x18\x01\"\xd4\x02\n" +
	"\fTaskProgress\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12&\n" +
	"\x06status\x18\x02 \x01(\x0e2\x0e.a2a.TaskStateR\x06status\x12)\n" +
	"\x10progress_message\x18\x03 \x01(\tR\x0fprogressMessage\x12/\n" +
	"\x13progress_percentage\x18\x04 \x01(\x05R\x12progressPercentage\x12<\n" +
	"\rprogress_data\x18\x05 \x01(\v2\x17.google.protobuf.StructR\fprogressData\x12*\n" +
	"\x11executor_agent_id\x18\x06 \x01(\tR\x0fexecutorAgentId\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt:\x02\x18\x01*u\n" +
	"\bPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPRIORITY_LOW\x10\x01\x12\x13\n" +
	"\x0fPRIORITY_MEDIUM\x10\x02\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x03\x12\x15\n" +
	"\x11PRIORITY_CRITICAL\x10\x042\xb9\x06\n" +
	"\bAgentHub\x12L\n" +
	"\x0ePublishMessage\x12\x1f.agenthub.PublishMessageRequest\x1a\x19.agenthub.PublishResponse\x12R\n" +
	"\x11PublishTaskUpdate\x12\".agenthub.PublishTaskUpdateRequest\x1a\x19.agenthub.PublishResponse\x12V\n" +
	"\x13PublishTaskArtifact\x12$.agenthub.PublishTaskArtifactRequest\x1a\x19.agenthub.PublishResponse\x12S\n" +
	"\x13SubscribeToMessages\x12$.agenthub.SubscribeToMessagesRequest\x1a\x14.agenthub.AgentEvent0\x01\x12M\n" +
	"\x10SubscribeToTasks\x12!.agenthub.SubscribeToTasksRequest\x1a\x14.agenthub.AgentEvent0\x01\x12Y\n" +
	"\x16SubscribeToAgentEvents\x12'.agenthub.SubscribeToAgentEventsRequest\x1a\x14.agenthub.AgentEvent0\x01\x12.\n" +
	"\aGetTask\x12\x18.agenthub.GetTaskRequest\x1a\t.a2a.Task\x124\n" +
	"\n" +
	"CancelTask\x12\x1b.agenthub.CancelTaskRequest\x1a\t.a2a.Task\x12D\n" +
	"\tListTasks\x12\x1a.agenthub.ListTasksRequest\x1a\x1b.agenthub.ListTasksResponse\x126\n" +
	"\fGetAgentCard\x12\x16.google.protobuf.Empty\x1a\x0e.a2a.AgentCard\x12P\n" +
	"\rRegisterAgent\x12\x1e.agenthub.RegisterAgentRequest\x1a\x1f.agenthub.RegisterAgentResponseB\x10Z\x0eevents/a2a;a2ab\x06proto3"

var (
	file_proto_eventbus_proto_rawDescOnce sync.Once
	file_proto_eventbus_proto_rawDescData []byte
)

func file_proto_eventbus_proto_rawDescGZIP() []byte {
	file_proto_eventbus_proto_rawDescOnce.Do(func() {
		file_proto_eventbus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_eventbus_proto_rawDesc), len(file_proto_eventbus_proto_rawDesc)))
	})
	return file_proto_eventbus_proto_rawDescData
}

var file_proto_eventbus_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_eventbus_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_eventbus_proto_goTypes = []any{
	(Priority)(0),                         // 0: agenthub.Priority
	(*AgentEvent)(nil),                    // 1: agenthub.AgentEvent
	(*AgentEventMetadata)(nil),            // 2: agenthub.AgentEventMetadata
	(*TaskStatusUpdateEvent)(nil),         // 3: agenthub.TaskStatusUpdateEvent
	(*TaskArtifactUpdateEvent)(nil),       // 4: agenthub.TaskArtifactUpdateEvent
	(*AgentCardEvent)(nil),                // 5: agenthub.AgentCardEvent
	(*PublishMessageRequest)(nil),         // 6: agenthub.PublishMessageRequest
	(*PublishTaskUpdateRequest)(nil),      // 7: agenthub.PublishTaskUpdateRequest
	(*PublishTaskArtifactRequest)(nil),    // 8: agenthub.PublishTaskArtifactRequest
	(*PublishResponse)(nil),               // 9: agenthub.PublishResponse
	(*SubscribeToMessagesRequest)(nil),    // 10: agenthub.SubscribeToMessagesRequest
	(*SubscribeToTasksRequest)(nil),       // 11: agenthub.SubscribeToTasksRequest
	(*SubscribeToAgentEventsRequest)(nil), // 12: agenthub.SubscribeToAgentEventsRequest
	(*GetTaskRequest)(nil),                // 13: agenthub.GetTaskRequest
	(*CancelTaskRequest)(nil),             // 14: agenthub.CancelTaskRequest
	(*ListTasksRequest)(nil),              // 15: agenthub.ListTasksRequest
	(*ListTasksResponse)(nil),             // 16: agenthub.ListTasksResponse
	(*RegisterAgentRequest)(nil),          // 17: agenthub.RegisterAgentRequest
	(*RegisterAgentResponse)(nil),         // 18: agenthub.RegisterAgentResponse
	(*TaskMessage)(nil),                   // 19: agenthub.TaskMessage
	(*TaskResult)(nil),                    // 20: agenthub.TaskResult
	(*TaskProgress)(nil),                  // 21: agenthub.TaskProgress
	(*timestamppb.Timestamp)(nil),         // 22: google.protobuf.Timestamp
	(*Message)(nil),                       // 23: a2a.Message
	(*Task)(nil),                          // 24: a2a.Task
	(*TaskStatus)(nil),                    // 25: a2a.TaskStatus
	(*structpb.Struct)(nil),               // 26: google.protobuf.Struct
	(*Artifact)(nil),                      // 27: a2a.Artifact
	(*AgentCard)(nil),                     // 28: a2a.AgentCard
	(TaskState)(0),                        // 29: a2a.TaskState
	(*emptypb.Empty)(nil),                 // 30: google.protobuf.Empty
}
var file_proto_eventbus_proto_depIdxs = []int32{
	22, // 0: agenthub.AgentEvent.timestamp:type_name -> google.protobuf.Timestamp
	23, // 1: agenthub.AgentEvent.message:type_name -> a2a.Message
	24, // 2: agenthub.AgentEvent.task:type_name -> a2a.Task
	3,  // 3: agenthub.AgentEvent.status_update:type_name -> agenthub.TaskStatusUpdateEvent
	4,  // 4: agenthub.AgentEvent.artifact_update:type_name -> agenthub.TaskArtifactUpdateEvent
	5,  // 5: agenthub.AgentEvent.agent_card:type_name -> agenthub.AgentCardEvent
	2,  // 6: agenthub.AgentEvent.routing:type_name -> agenthub.AgentEventMetadata
	0,  // 7: agenthub.AgentEventMetadata.priority:type_name -> agenthub.Priority
	25, // 8: agenthub.TaskStatusUpdateEvent.status:type_name -> a2a.TaskStatus
	26, // 9: agenthub.TaskStatusUpdateEvent.metadata:type_name -> google.protobuf.Struct
	27, // 10: agenthub.TaskArtifactUpdateEvent.artifact:type_name -> a2a.Artifact
	26, // 11: agenthub.TaskArtifactUpdateEvent.metadata:type_name -> google.protobuf.Struct
	28, // 12: agenthub.AgentCardEvent.agent_card:type_name -> a2a.AgentCard
	26, // 13: agenthub.AgentCardEvent.metadata:type_name -> google.protobuf.Struct
	23, // 14: agenthub.PublishMessageRequest.message:type_name -> a2a.Message
	2,  // 15: agenthub.PublishMessageRequest.routing:type_name -> agenthub.AgentEventMetadata
	3,  // 16: agenthub.PublishTaskUpdateRequest.update:type_name -> agenthub.TaskStatusUpdateEvent
	2,  // 17: agenthub.PublishTaskUpdateRequest.routing:type_name -> agenthub.AgentEventMetadata
	4,  // 18: agenthub.PublishTaskArtifactRequest.artifact:type_name -> agenthub.TaskArtifactUpdateEvent
	2,  // 19: agenthub.PublishTaskArtifactRequest.routing:type_name -> agenthub.AgentEventMetadata
	29, // 20: agenthub.SubscribeToTasksRequest.states:type_name -> a2a.TaskState
	29, // 21: agenthub.ListTasksRequest.states:type_name -> a2a.TaskState
	24, // 22: agenthub.ListTasksResponse.tasks:type_name -> a2a.Task
	28, // 23: agenthub.RegisterAgentRequest.agent_card:type_name -> a2a.AgentCard
	26, // 24: agenthub.TaskMessage.parameters:type_name -> google.protobuf.Struct
	22, // 25: agenthub.TaskMessage.deadline:type_name -> google.protobuf.Timestamp
	0,  // 26: agenthub.TaskMessage.priority:type_name -> agenthub.Priority
	26, // 27: agenthub.TaskMessage.metadata:type_name -> google.protobuf.Struct
	22, // 28: agenthub.TaskMessage.created_at:type_name -> google.protobuf.Timestamp
	29, // 29: agenthub.TaskResult.status:type_name -> a2a.TaskState
	26, // 30: agenthub.TaskResult.result:type_name -> google.protobuf.Struct
	22, // 31: agenthub.TaskResult.completed_at:type_name -> google.protobuf.Timestamp
	26, // 32: agenthub.TaskResult.execution_metadata:type_name -> google.protobuf.Struct
	29, // 33: agenthub.TaskProgress.status:type_name -> a2a.TaskState
	26, // 34: agenthub.TaskProgress.progress_data:type_name -> google.protobuf.Struct
	22, // 35: agenthub.TaskProgress.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 36: agenthub.AgentHub.PublishMessage:input_type -> agenthub.PublishMessageRequest
	7,  // 37: agenthub.AgentHub.PublishTaskUpdate:input_type -> agenthub.PublishTaskUpdateRequest
	8,  // 38: agenthub.AgentHub.PublishTaskArtifact:input_type -> agenthub.PublishTaskArtifactRequest
	10, // 39: agenthub.AgentHub.SubscribeToMessages:input_type -> agenthub.SubscribeToMessagesRequest
	11, // 40: agenthub.AgentHub.SubscribeToTasks:input_type -> agenthub.SubscribeToTasksRequest
	12, // 41: agenthub.AgentHub.SubscribeToAgentEvents:input_type -> agenthub.SubscribeToAgentEventsRequest
	13, // 42: agenthub.AgentHub.GetTask:input_type -> agenthub.GetTaskRequest
	14, // 43: agenthub.AgentHub.CancelTask:input_type -> agenthub.CancelTaskRequest
	15, // 44: agenthub.AgentHub.ListTasks:input_type -> agenthub.ListTasksRequest
	30, // 45: agenthub.AgentHub.GetAgentCard:input_type -> google.protobuf.Empty
	17, // 46: agenthub.AgentHub.RegisterAgent:input_type -> agenthub.RegisterAgentRequest
	9,  // 47: agenthub.AgentHub.PublishMessage:output_type -> agenthub.PublishResponse
	9,  // 48: agenthub.AgentHub.PublishTaskUpdate:output_type -> agenthub.PublishResponse
	9,  // 49: agenthub.AgentHub.PublishTaskArtifact:output_type -> agenthub.PublishResponse
	1,  // 50: agenthub.AgentHub.SubscribeToMessages:output_type -> agenthub.AgentEvent
	1,  // 51: agenthub.AgentHub.SubscribeToTasks:output_type -> agenthub.AgentEvent
	1,  // 52: agenthub.AgentHub.SubscribeToAgentEvents:output_type -> agenthub.AgentEvent
	24, // 53: agenthub.AgentHub.GetTask:output_type -> a2a.Task
	24, // 54: agenthub.AgentHub.CancelTask:output_type -> a2a.Task
	16, // 55: agenthub.AgentHub.ListTasks:output_type -> agenthub.ListTasksResponse
	28, // 56: agenthub.AgentHub.GetAgentCard:output_type -> a2a.AgentCard
	18, // 57: agenthub.AgentHub.RegisterAgent:output_type -> agenthub.RegisterAgentResponse
	47, // [47:58] is the sub-list for method output_type
	36, // [36:47] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_proto_eventbus_proto_init() }
func file_proto_eventbus_proto_init() {
	if File_proto_eventbus_proto != nil {
		return
	}
	file_proto_a2a_core_proto_init()
	file_proto_eventbus_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentEvent_Message)(nil),
		(*AgentEvent_Task)(nil),
		(*AgentEvent_StatusUpdate)(nil),
		(*AgentEvent_ArtifactUpdate)(nil),
		(*AgentEvent_AgentCard)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_eventbus_proto_rawDesc), len(file_proto_eventbus_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_eventbus_proto_goTypes,
		DependencyIndexes: file_proto_eventbus_proto_depIdxs,
		EnumInfos:         file_proto_eventbus_proto_enumTypes,
		MessageInfos:      file_proto_eventbus_proto_msgTypes,
	}.Build()
	File_proto_eventbus_proto = out.File
	file_proto_eventbus_proto_goTypes = nil
	file_proto_eventbus_proto_depIdxs = nil
}
